Move CI checks to Github Actions
matrix-org/python-canonicaljson pull request #41
Opened 2021-10-04 20:38 UTC by H-Shay

Fixes #38. Moved CI checks to Github Actions, removed old Travis configs, and reformatted some code that was failing `black` invocation.

2021-10-04 21:47 UTC, H-Shay commented
One thing I want to note is that the unit test invocations are failing because they are set to fail if coverage is below 100%. The test coverage is currently at 85% due to the fact that either lines 26-30 OR lines 31-35 will be tested depending on which `frozendict` implementation (c-extension or no c-extension) the user is running, thus preventing us from having 100% coverage. I will see what I can do about that in another PR but I wanted to mention it.

2021-10-05 10:54 UTC, DMRobertson requested changes
We could reduce some of the deduplication here using a [`strategy.matrix`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix). https://github.com/matrix-org/synapse/blob/develop/.github/workflows/tests.yml is an example.

I'd be tempted to have one matrix for linting (black and pep8); one for the two packaging jobs, and one for the unit tests.

2021-10-05 10:54 UTC, DMRobertson commented on .github/workflows/tests.yaml
> +  run-unit-tests-38:
I think we should also run these tests on 3.9 and the recently released 3.10 (if setup-python supports it)

2021-10-05 10:56 UTC, DMRobertson commented on .github/workflows/tests.yaml
> +  run-unit-tests-38:
Looks like 3.10 is supported as of about three hours ago! https://github.com/actions/python-versions/releases/tag/3.10.0-117470

2021-10-05 11:53 UTC, DMRobertson commented
> One thing I want to note is that the unit test invocations are failing because they are set to fail if coverage is below 100%. The test coverage is currently at 85% due to the fact that either lines 26-30 OR lines 31-35 will be tested depending on which `frozendict` implementation (c-extension or no c-extension) the user is running, thus preventing us from having 100% coverage. I will see what I can do about that in another PR but I wanted to mention it.

I think "coverage combine" might be what we want here. Not familiar with the details, but maybe https://github.com/matrix-org/synapse/blob/6fcc3e0bc81b4ed738eee702b0e1d193c052d205/tox.ini#L174-L182 is of interest?

2021-10-05 17:51 UTC, H-Shay commented
A few things: I am wondering if we can exclude the code that is specific to the c-implementation of frozendict from the coverage report. This code path is not touched at all unless the test runner is using the `frozendict` c-implementation, and the only way to ensure that is to ensure that the test runner (like a Github Actions runner) uses that specific implementation, which seems odd. This is the code that is causing the `coverage --fail-under-100` invocation to fail and blowing up the CI. 

Second, re: adding python 3.10-this blows up on the `nose` invocation, and it looks like `nose` is on it's way to being unmaintained: https://nose.readthedocs.io/en/latest/. In this case does it make sense to switch the dependency to something else, or to hold off on upgrading to python 3.10?

2021-10-05 18:37 UTC, DMRobertson commented
> A few things: I am wondering if we can exclude the code that is specific to the c-implementation of frozendict from the coverage report. This code path is not touched at all unless the test runner is using the `frozendict` c-implementation, and the only way to ensure that is to ensure that the test runner (like a Github Actions runner) uses that specific implementation, which seems odd. This is the code that is causing the `coverage --fail-under-100` invocation to fail and blowing up the CI.

It'd be nice to have something that checks this works in both modes. But I'm not sure there's an easy way to explicitly say "please install frozendict with the C extension" and "please install without it". (I couldn't see anything in its [setup.py](https://github.com/Marco-Sulla/python-frozendict/blob/master/setup.py), anyway.) Given that, I think it's not worth the effort to account for both options here.

Suggestions:

- drop coverage arg `--fail-under-100`
- relax to `--fail-under=80` (for example)
- ignore as in 5c5f81c

> Second, re: adding python 3.10-this blows up on the `nose` invocation, and it looks like `nose` is on it's way to being unmaintained: https://nose.readthedocs.io/en/latest/. In this case does it make sense to switch the dependency to something else, or to hold off on upgrading to python 3.10?

Ouch---looks like something changed from deprecated to removed in 3.10 I think? That link suggests:

>  New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

Maybe we can replace `nose` with `python -m unittest`? (If so, I'd suggest sanity checking that we're using the right Python version by e.g. calling `python --version`. I'm guessing that tox and the setup-python action will mean this just works, but... just a small bit of paranoia on my part there.)

If that doesn't work, I'd suggest giving nose2 a try.

2021-10-06 09:43 UTC, DMRobertson commented
See https://github.com/H-Shay/python-canonicaljson/actions/runs/1309035566 for an example of this run in action

2021-10-06 09:47 UTC, DMRobertson approved these changes
LGTM!

2021-10-06 09:47 UTC, DMRobertson commented on .github/workflows/tests.yaml
> +        python-version: ["3.8", "3.9", "3.10"]
I wasn't sure why we need to worry about macos specifically here. Looking at the history of the Travis CI config I found https://github.com/matrix-org/python-canonicaljson/commit/91009169bf6bed493d8c9f8360d1d3ec922fb045, which seems to suggest there were some string/byte encoding fun and games.

2021-10-07 15:54 UTC, merged